### ISSUE TITLE
When initializing a new database it causes CM to fail /status/ checks

### ISSUE THREAD

**Issue by mostlygeek** [jrconlin/campaign_manager#5]
When new database tables are created by the application it inserts a "test" record into the "campaign" table by default. This causes the app's /status/ page to fail and seems to cause issues elsewhere. 

Can this behavior be removed or fixed?

**Comment by jrconlin** [comment]
There is a "health_check" routine that inserts and then removes a "test" record. This is normally pref'd "off" unless the "dbg.self_diag = True" flag is set.

Is this causing the problem?

**Comment by mostlygeek** [comment]
Checked the configs and "dbg.self_diag" doesn't exist. It only causes an issue when CM is given a blank database. After deleting the record it is smooth sailing after that.

**Comment by mostlygeek** [comment]
Been unable to reproduce this error, going to assume the latest fix clears it up. Closing for now. Will re-open if this becomes an issue in the future.
