### ISSUE TITLE
Adding multibyte characters makes the app unable to create new campaigns

### ISSUE THREAD

**Issue by mostlygeek** [jrconlin/campaign_manager#8]
original bug: https://bugzilla.mozilla.org/show_bug.cgi?id=959750
- the ORM layer creates table with the latin-1 character set 
- not sure if the above causes the issues

**Comment by jrconlin** [comment]
fixed https://github.com/mozilla-services/campaign_manager/commit/7d3f595ccb46a46bb44765edfe7345c0dc3cabb4

Please Note:

The following MySQL command must be executed on existing databases concurrent with installing latest version:
    alter table campaigns convert to character set utf8;

This command is included in sql/20140114_sql_patch.sql
